server:
  port: 50550
wise:
  api-url: https://api.wise.com
  oauth-token: ${WISE_TOKEN}
  public-key: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvO8vXV+JksBzZAY6GhSO
               XdoTCfhXaaiZ+qAbtaDBiu2AGkGVpmEygFmWP4Li9m5+Ni85BhVvZOodM9epgW3F
               bA5Q1SexvAF1PPjX4JpMstak/QhAgl1qMSqEevL8cmUeTgcMuVWCJmlge9h7B1CS
               D4rtlimGZozG39rUBDg6Qt2K+P4wBfLblL0k4C4YUdLnpGYEDIth+i8XsRpFlogx
               CAFyH9+knYsDbR43UJ9shtc42Ybd40Afihj8KnYKXzchyQ42aC8aZ/h5hyZ28yVy
               Oj3Vos0VdBIs/gAyJ/4yyQFCXYte64I7ssrlbGRaco4nKF3HmaNhxwyKyJafz19e
               HwIDAQAB'
  ruleset:
    default:
      min-deposit-amount: 10
      max-deposit-amount: 200
      percentage: 100
    EUR:
      min-deposit-amount: 20
      max-deposit-amount: 200
      percentage: 50
    GBP:
      min-deposit-amount: 25
      max-deposit-amount: 200