version: '3.7'
services:
  ngrok:
    image: nginx
    volumes:
      - ../ngrok-exec:/ngrok-exec/
    command: /ngrok-exec/ngrok http 80 -config=/ngrok-exec/ngrok.conf
#  links:
#    - php
#  ports:
#    - 4040:4040